# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@14

jobs:
  job_1:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: |
            yarn
      - run:
          name: Generate Publish Files
          command: |
            yarn generate
      - run:
          name: Create Folder for Published files
          command: |
            mkdir dist-zip

workflows:
  workflow_1:
    jobs:
      - job_1
